cc = gcc
INCLUDE = include
LIB = lib
LIBBIN = $(LIB)/bin
LIBSRC = $(LIB)/src
LIBSRCA = $(LIBSRC)/arithmetic
LIBSRCB = $(LIBSRC)/bitwise
SRC = src
SRCA1 = $(SRC)/app1
SRCA2 = $(SRC)/app2

VPATH = $(INCLUDE) $(LIBBIN) $(LIBSRC) $(LIBSRCA) $(LIBSRCB) $(SRCA1) $(SRCA2)
CPPFLAG= -I $(INCLUDE)
MAKE = make -f
